version: '3'

networks:
  hohoho:

services:
  trello-api:
    security_opt:
      - seccomp:unconfined
    build:
      context: .
      args:
        - VER=1.0
    ports:
      - "80:8080"
      - "443:443"
      - "40000:40000"
    depends_on:
      - postgres
      - redis
      # - security-service
    networks:
      - hohoho
    environment:
      - DEPLOYAPI
    tty: true
    stdin_open: true

  security:
    build:
      context: .
      dockerfile: ./session_service/Dockerfile
      args:
        - VER=1.0
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - hohoho
    environment:
      - DEPLOYAPI
    tty: true
    stdin_open: true

  file-loader:
    build:
      context: .
      dockerfile: ./file_service/Dockerfile
      args:
        - VER=1.0
    ports:
      - "8082:8082"
    networks:
      - hohoho
    environment:
      - DEPLOYAPI
    tty: true
    stdin_open: true

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: trello
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:
      - "5432:5432"
    networks:
      - hohoho

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - hohoho

