version: '3'

networks:
  hohoho:

services:
  trello-api:
    build:
      context: .
      args:
        - VER=1.0
    ports:
      - "80:8080"
      - "443:443"
    depends_on:
      - postgres
      - redis
    networks:
      - hohoho
    environment:
      - DEPLOYAPI

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: trello
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:
      - "8001:5432"
    networks:
      - hohoho

  redis:
    image: redis:alpine
    ports:
      - "6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - hohoho

